# Generated by Django 4.2.7 on 2025-06-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["-priority", "name"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                default=2,
                help_text="User who created this organization",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(
                blank=True, help_text="Role description", verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Role priority (higher number = higher priority)",
                verbose_name="priority",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                help_text="Role name",
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.RemoveField(
            model_name="role",
            name="organization",
        ),
    ]
